[tool.poetry]
name = "putao"
version = "0.4.0"
description = "Poor man's UTAU"
authors = ["Ong Yong Xin <ongyongxin2020+github@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ongyx/putao"
classifiers = [
    "Topic :: Multimedia :: Sound/Audio :: Sound Synthesis",
]

[tool.poetry.dependencies]
python = "^3.11"
chardet = "^5.2.0"
click = "^8.1.7"
mido = "^1.3.0"
numpy = "^1.25.2"
pydub = {git = "https://github.com/jiaaro/pydub"}
pyworld = "^0.3.4"
soundfile = "^0.12.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"

[tool.poetry.scripts]
putao = "putao.cli:cli"

[tool.pyright]
venvPath = "."
venv = ".venv"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
