[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "putao"
author = "Ong Yong Xin"
author-email = "ongyongxin2020+github@gmail.com"
home-page = "https://github.com/ongyx/putao"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
description-file = "README.md"
requires = [
    "chardet>=4.0.0",
    "click>=7.1.2",
    #"librosa>=0.8.0",
    "mido>=1.2.9",
    "numpy>=1.20.0",
    "pydub>=0.25.1",
    "pyparsing>=2.4.7",
    "pyrubberband>=0.3.0",
    "pyworld>=0.2.12",
    "SoundFile>=0.10.3",
]
requires-python = ">=3.6"

[tool.flit.metadata.requires-extra]
test = [
    "pytest>=6.2.2"
]

[tool.flit.scripts]
putao = "putao.cli:cli"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rP"
